name: release

on:
  push:
    tags: ["v*"]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    concurrency:
      group: publish-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          lookup-only: true
      - run: cargo test --all
      - run: cargo publish --token "${CRATES_IO_API_KEY}"
        env:
          CRATES_IO_API_KEY: "${{ secrets.CRATES_IO_API_KEY }}"
